################################################################################
# System Environment Variables
################################################################################
export XDG_CONFIG_HOME="$HOME/.config"
export XDG_CACHE_HOME="$HOME/.cache"
export XDG_DATA_HOME="$HOME/.local/share"

################################################################################
# Application Environment Variables
################################################################################
export STARSHIP_CONFIG="$XDG_CONFIG_HOME/starship/starship.toml"
export ZSH_SESSION_DIR="$XDG_CONFIG_HOME/zsh/zsh_sessions"
export PATH="$HOME/.local/share/npm-global/bin:/opt/homebrew/bin:$PATH"
export DOCKER_CONFIG="$XDG_CONFIG_HOME/docker"
export NVM_DIR="$XDG_CONFIG_HOME/nvm"
export NPM_CONFIG_USERCONFIG="$HOME/.config/npm/npmrc"
export NPM_CONFIG_CACHE="$HOME/.config/npm/cache"
export EZA_CONFIG_DIR="$XDG_CONFIG_HOME/eza"

export HISTFILE="$XDG_CONFIG_HOME/zsh/zsh_history"
HISTSIZE=10000
SAVEHIST=10000

################################################################################
# Initialize Starship
################################################################################
eval "$(starship init zsh)"

[ -s "$(brew --prefix nvm)/nvm.sh" ] && . "$(brew --prefix nvm)/nvm.sh"

################################################################################
# Custom User Alias
################################################################################
alias vi="nvim"
alias vim="nvim"
alias ls="eza -1 --no-quotes"
